### ISSUE TITLE
ExtrinsicBuilder().xTokens() supports AccountKey20 only

### ISSUE THREAD

**Issue by nohaapav** [PureStake/xcm-sdk#121]
Currently xTokens pallet [builder](https://github.com/PureStake/xcm-sdk/blob/main/packages/builder/src/extrinsic/pallets/xTokens/xTokens.ts) supports only AccountKey20 so can't be used for:

- para -> para transfer (no EVM based)
- para -> relay transfer (no EVM based)

Account type should be build based on parachain type e.g.
```
const accountType = destination.isEvmParachain() ? 'AccountKey20' : 'AccountId32';
```

In such case EtherSigner should be optional .. See [getTransferData](https://github.com/PureStake/xcm-sdk/blob/main/packages/sdk/src/getTransferData/getTransferData.ts#L29)

**Comment by ekenigs** [comment]
@nohaapav, thanks again. Here is [the same answer](https://github.com/PureStake/xcm-sdk/issues/122#issuecomment-1689375628) as on your other issue.
