### ISSUE TITLE
Introduce optional configuration for SDK

### ISSUE THREAD

**Issue by nohaapav** [PureStake/xcm-sdk#122]
Currently [ConfigBuilder](https://github.com/PureStake/xcm-sdk/blob/main/packages/config/src/ConfigBuilder/ConfigBuilder.ts) and [Sdk](https://github.com/PureStake/xcm-sdk/blob/main/packages/sdk/src/sdk.ts) are tightly coupled and there is no easy way to pass custom configuration unless PR. 

It would be great if user can do so for several reasons:

- user want to customize asset list, no. of supported chains, or chain config without additional filtering done on top of Sdk
- new user want to test non-existing asset/chain/chainConfig. Currently the only way is to clone the repository.
- user want to feed up Sdk with dynamic configuration instead of static one (e.g. from chopsticks every x hours)

To make these 2 builders loose coupled in 2 easy steps:

- Introduce optional param in ConfigBuilder covering custom (assetMap, chainMap, chainConfigMap)
- Introduce optional param in Sdk for ConfigBuilder

**Comment by ekenigs** [comment]
Hey @nohaapav, thanks for your feedback. It's always welcome.

It makes sense. We are busy with other projects, so if you want this change sooner than later, a PR is welcome. Otherwise, you should need to wait.

**Comment by ekenigs** [comment]
It was changed in #124.
